version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  database:
    restart: always
    image: postgres:13-alpine
    container_name: jotpad_db
    environment:
      - POSTGRES_PASSWORD=jotpad_dev
      - POSTGRES_USER=jotpad_dev
      - POSTGRES_DB=jotpad_dev
    ports:
      - "8092:5432" # to avoid local ports from clashing
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jotpad_dev"]
      interval: 5s
      timeout: 10s
      retries: 5

  # Using traefik as reverse proxy
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    restart: always
    container_name: jotpad_web
    user: "root:jotpad"
    build: .
    volumes:
      - .:/app
    labels:
      - "traefik.http.routers.web.rule=Host(`jotpad.docker.localhost`)"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      pwd
      poetry run pad/manage.py makemigrations
      poetry run pad/manage.py migrate
      echo "from django.contrib.auth.models import User; User.objects.filter(email='jotpad@example.com').delete(); User.objects.create_superuser('devadmin', 'jotpad@example.com', 'padjot')" | poetry run pad/manage.py shell
      echo Starting Django development server..
      poetry run pad/manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=jotpad.settings.dev
      - DATABASE_URL=postgresql://jotpad_dev:jotpad_dev@database:5432/jotpad_dev
      - POSTGRES_DB=jotpad_dev
      - POSTGRESDB_PORT=5432
      - POSTGRES_USER=jotpad_dev
      - POSTGRES_PASSWORD=jotpad_dev
      - POSTGRESDB_HOST=database

networks:
  default:
      name: jotpad
